# Generated by Django 3.2.23 on 2023-12-13 14:54

from django.db import migrations, models
import music_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=music_api.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
